services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
    - ./nginx/conf.d:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

  node1:
    container_name: CS1
    image: "node:18"
    user: "node"
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/node1:/home/node
      - ./public:/home/public
      - ./frontend/build:/home/frontend/build
    ports:
      - "8082:8080"
      ##- "127.0.0.1:9229:9229"
    command: "npm start"

  node2:
    container_name: CS2
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/node2:/home/node/app
    ports:
      - "8083:8080"
    command: "npm start"

  node3:
    container_name: CS3
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/node3:/home/node/app
    ports:
      - "8084:8080"
    command: "npm start"

  node4:
    container_name: CS4
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/node4:/home/node/app
    ports:
      - "8085:8080"
    command: "npm start"

## U: postgres -- P: password
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 808:8080

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: waliur@waliur.com
      PGADMIN_DEFAULT_PASSWORD: waliur
