services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
    - ./nginx/conf.d:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

  node1:
    container_name: node1
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/node1:/home/node/app
    ports:
      - "8081:8080"
    command: "npm start"

  node2:
    container_name: node2
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/node2:/home/node/app
    ports:
      - "8082:8080"
    command: "npm start"